### ISSUE TITLE
Does not support inputting values in a 2d array

### ISSUE THREAD

**Issue by salman660** [PseudocodeEditor/editor#27]
Let me First appreciate how great it is and how much it has helped me in doing GCSE pseudocode programs, you guys have done fantastic job!

But unfortunately i encountered an issue while using it which I firmly believe will be fixed soon. 

The issue is :

**Does not support inputting values in a 2d array**

![image](https://user-images.githubusercontent.com/56877461/235242241-d9bff84b-95a7-4f4f-a0fd-92f4b99dc2ad.png)

**Comment by Coding-Cactus** [comment]
Hi there @salman660, inputting directly into a 2D array is not defined in the [CIE PseudoCode Spec](https://pastpapers.co/cie/A-Level/Computer%20Science%20(for%20first%20examination%20in%202021)%20(9618)/Syllabus%20&%20Specimen/9618_y21_sg.pdf), so what I'd suggest you do instead is input to another variable and then copy into your array. 

Something like this:
![image](https://user-images.githubusercontent.com/65423356/235306036-c102625e-01e4-407a-9425-afdc4d9a196e.png)
